version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    environment:
      - 'node.name=BAE'
      - 'discovery.type=single-node'
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
    ports:
      - "127.0.0.1:9200:9200"
    networks:
      main:
        aliases:
          - elastic.docker

  mongo:
    image: mongo:3.2
    ports:
      - 27017:27017
    networks:
      main:
    volumes:
      - ./proxy-data:/data/db

  mysql:
    image: mysql:5.7
    #restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      main:
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw      

networks:
  main:
    external: true
